name: Build and push workflow

on:
  push:
    branches:
      - main
  pull_request: {}


jobs:
  GenerateImageVersion:
    name: ID Vilnius Generate Image Version
    uses: idvilnius/gha-workflows/.github/workflows/image-version.yaml@main

  Build:
    name: ID Vilnius Build image
    needs: [GenerateImageVersion]
    uses: idvilnius/gha-workflows/.github/workflows/build-env.yaml@main
    with:
      docker_image: ${{ vars.AZURE_CONTAINER_REGISTRY }}
      image_tag: ${{ needs.GenerateImageVersion.outputs.image_version }}
      build_step: |
        docker build -t "${{ vars.AZURE_CONTAINER_REGISTRY }}:${{ needs.GenerateImageVersion.outputs.image_version }}" .
    secrets: inherit

  Security:
    name: 🔐 ID Vilnius Security Scan
    needs: [GenerateImageVersion, Build]
    uses: idvilnius/gha-workflows/.github/workflows/security.yaml@main
    with:
      docker_image: ${{ vars.AZURE_CONTAINER_REGISTRY }}
      image_tag: ${{ needs.GenerateImageVersion.outputs.image_version }}

  PublishDev:
    name: 📦 ID Vilnius Publish to ACR
    needs: [GenerateImageVersion, Security]
    if: ${{ github.ref == 'refs/heads/staging-sview-infra' }}
    uses: idvilnius/gha-workflows/.github/workflows/publish-acr.yaml@main
    with:
      docker_image: ${{ vars.AZURE_CONTAINER_REGISTRY }}
      image_tag: ${{ needs.GenerateImageVersion.outputs.image_version }}
    secrets:
      acr_username: ${{ secrets.ACR_USERNAME }}
      acr_password: ${{ secrets.ACR_PASSWORD }}

#trigger build